services:
  postgres:
    image: 'postgres:17'
    environment:
      - 'POSTGRES_DB=senior_project'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=1832003'
    ports:
      - '5432:5432'
    volumes:
      - 'pg-data:/var/lib/postgresql/data'
    networks:
      - 'mynetwork'

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    networks:
      - 'mynetwork'

networks:
  mynetwork:

volumes:
  pg-data:
